version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: lan-monitor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./config:/app/config
      - ./database:/app/database
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - lan-monitor-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: lan-monitor-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env:/app/.env
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - lan-monitor-network
    restart: unless-stopped

networks:
  lan-monitor-network:
    driver: bridge

volumes:
  database: