FROM node:18-alpine

WORKDIR /app

# package.jsonとpackage-lock.jsonのコピー
COPY frontend/package*.json ./

# 依存関係のインストール
RUN npm install

# アプリケーションコードのコピー
COPY frontend ./

EXPOSE 3000

CMD ["npm", "start"]